sudo: false

language: nodejs

node_js:
  - node

install:
  - npm ci
  - cd client && npm install && cd ../

script:
  - npm run lint
  - npm install jest -g
  - npm run test:coveralls

notifications: email:false
