sudo: false

language: nodejs

node_js:
  - node

install:
  - npm ci
  - cd client && npm install && cd ../

script:
  - npm install -g jest
  - npm run lint
  - npm run test:coverage
  #- npm run test::coveralls

notifications: email:false
