export const SET_USER = 'SET_USER'
export const RESET_USER = 'RESET_USER'
export const SET_SEARCH = 'SET_SEARCH'
export const SET_FILTERS = 'SET_FILTERS'
export const RESET_SEARCH = 'RESET_SEARCH'
export const RESET_FILTERS = 'RESET_FILTERS'
export const SET_STATE = 'SET_STATE'
export const RESET_STATE = 'RESET_STATE'
